spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: username
    password: password
    url: jdbc:oracle:thin:@HOST:PORT/SID OR SERVICE

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

logging:
  level:
    com.example.sbjsp: debug